// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBndgKguCdjEl1XABo_r8wnf0LR1HjzqY4',
    appId: '1:368644106325:web:3b9901e88b937a4fd28cdc',
    messagingSenderId: '368644106325',
    projectId: 'pertemuan4-aura-7ba61',
    authDomain: 'pertemuan4-aura-7ba61.firebaseapp.com',
    storageBucket: 'pertemuan4-aura-7ba61.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIl_qoIAhxfNwRPR4oAnUMdDjfb7G5FBQ',
    appId: '1:368644106325:android:5cafb81a51afda27d28cdc',
    messagingSenderId: '368644106325',
    projectId: 'pertemuan4-aura-7ba61',
    storageBucket: 'pertemuan4-aura-7ba61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTxOVpa-MtohWMnyvxymL2-Bqy0kTTU6w',
    appId: '1:368644106325:ios:82a0225404f80796d28cdc',
    messagingSenderId: '368644106325',
    projectId: 'pertemuan4-aura-7ba61',
    storageBucket: 'pertemuan4-aura-7ba61.firebasestorage.app',
    iosBundleId: 'com.example.uasTokoBaju',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTxOVpa-MtohWMnyvxymL2-Bqy0kTTU6w',
    appId: '1:368644106325:ios:82a0225404f80796d28cdc',
    messagingSenderId: '368644106325',
    projectId: 'pertemuan4-aura-7ba61',
    storageBucket: 'pertemuan4-aura-7ba61.firebasestorage.app',
    iosBundleId: 'com.example.uasTokoBaju',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBndgKguCdjEl1XABo_r8wnf0LR1HjzqY4',
    appId: '1:368644106325:web:33867d794b34449dd28cdc',
    messagingSenderId: '368644106325',
    projectId: 'pertemuan4-aura-7ba61',
    authDomain: 'pertemuan4-aura-7ba61.firebaseapp.com',
    storageBucket: 'pertemuan4-aura-7ba61.firebasestorage.app',
  );
}
